version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "03:00"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
