[versions]
kotlin = "2.0.20"
detekt = "1.23.7"
kotest = "5.9.1"
jupiter = "5.11.1"
decompose = "3.1.0"
jreleaser = "1.14.0"

[libraries]
detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }

detekt-test = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }
kotest = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter" }

decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }

[bundles]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
