[versions]
kotlin = "2.3.0"
detekt = "2.0.0-alpha.2"
kotest = "5.9.1"
jupiter = "5.11.0"
decompose = "3.1.0"
jreleaser = "1.14.0"

[libraries]
detekt-api = { module = "dev.detekt:detekt-api", version.ref = "detekt" }
detekt-psi-utils = { module = "dev.detekt:detekt-psi-utils", version.ref = "detekt" }

detekt-test = { module = "dev.detekt:detekt-test", version.ref = "detekt" }
detekt-test-junit = { module = "dev.detekt:detekt-test-junit", version.ref = "detekt" }
kotest = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter" }

decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }

[bundles]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
